#bool EMERGENCY_STOP_STATU  #急停状态：1：急停中，0：急停解除
#bool SUCTION_CUP_STATUS     #吸盘状态：1：吸盘吸住中，0：吸盘解除
#bool MOTOR_STATUS			#履带电机状态：1：异常，0：正常
#bool BRUSH_STATUS			#辊刷状态：1：异常，0：正常
#bool DROP_SIGN				#跌落标志，1：防跌落触发，0：防跌落未触发
#int8 EXCEPTION_CODE			#异常码，预留

bool emergency_stop_status  #急停状态：1：急停中，0：急停解除
bool suction_cup_status     #吸盘状态：1：吸盘吸住中，0：吸盘解除
bool motor_status			#履带电机状态：1：异常，0：正常
bool brush_status			#辊刷状态：1：异常，0：正常
bool drop_sign				#跌落标志，1：防跌落触发，0：防跌落未触发
int8 exception_code			#异常码，预留