#bool EMERGENCY_STOP  # 0：不急停，1：急停
#bool SUCTION_CUP    # 0：不放吸盘, 1：放吸盘
#int8 LED_CONTROL	# 0: 关闭，1：绿灯常亮，2：绿灯闪亮，3：黄灯常亮，4：黄灯闪亮，5：红灯常亮，6：红灯闪亮
#int8 BUZZER_CONTROL	# 0: 关闭，1：蜂鸣器一直响，2：蜂鸣器长响一声后关，3：蜂鸣器长响两声后关
#int16 BRUSH_V		# 辊刷速度，RPM


bool emergency_stop  # 0：不急停，1：急停
bool suction_cup     # 0：不放吸盘, 1：放吸盘
int8 led_control	 # 0: 关闭，1：绿灯常亮，2：绿灯闪亮，3：黄灯常亮，4：黄灯闪亮，5：红灯常亮，6：红灯闪亮
int8 buzzer_control	 # 0: 关闭，1：蜂鸣器一直响，2：蜂鸣器长响一声后关，3：蜂鸣器长响两声后关
int16 brush_v		 # 辊刷速度，RPM
